### ISSUE TITLE
Return modality to the schema

### ISSUE THREAD

**Issue by shadowdoc** [RSNA/ACR-RSNA-CDEs#34]
@ccarr  - can someone let me know whether this exists in the current radelement site as an optional element, or is it just missing from our examples because it's optional?

If it's there, but missing in the schema, I'll add it now. Otherwise that's another future enhancement to request.

Apologies, I don't see other devs to "@"...

**Comment by shadowdoc** [comment]
Historical schema for reference

modality =
    element modality {
        element system { "RadLex" },
        ( element code {"CT"},
           element name { "Computed Tomography"},
           element url { "http://radlex.org/RID/RID10321" } ) ?,
        ( element code { "FL" },
          element name { "Fluoroscopy" },
          element url { "http://radlex.org/RID/RID10361" } ) ?,
        ( element code { "MR" },
          element name { "Magnetic Resonance Imaging" },
          element url { "http://radlex.org/RID/RID10312" } ) ?,
        ( element code { "NM" },
          element name { "Nuclear Medicine" },
          element url { "http://radlex.org/RID/RID10330" } ) ?,
        ( element code { "PET" },
          element name { "Positron Emission Tomography" },
          element url { "http://radlex.org/RID/RID10337" } ) ?,
        ( element code { "US" },
          element name { "Ultrasound" },
          element url { "http://radlex.org/RID/RID10326" } ) ?,
        ( element code { "XR" },
          element name { "Projection Radiography" },
          element url { "http://radlex.org/RID/RID10345" } ) ?
     }

**Comment by talkasab** [comment]
+1 for this fix.
I don't think we want authors putting modalities in the titles of their Sets, but rather in the metadata. Problem is, only way to do that now is to use a generiic index code.
