### ISSUE TITLE
Need versions of schema for different situations

### ISSUE THREAD

**Issue by talkasab** [RSNA/ACR-RSNA-CDEs#38]
We would like to have coordinated versions of the schema for:

- A set (what the schema currently does): `cde_set.schema.json`
- An element `cde_element.schema.json`
- List of sets `cde_set_list.schema.json`
- List of elements `cde_element_list.schema.json`

**Comment by talkasab** [comment]
Proposed solution:
- Split the current file into three working files that we actually author with:
  - `cde_set_components.schema.json`: Includes the Set definition and pieces specific to that
  - `cde_element_components.schema.json`: Includes all of the Elements definitions and pieces specific to it
  - `cde_common_components.schema.json`: Includes all of the pieces that are shared between Set and Element
- Create a simple script that combines the three files into the four final schema files that are actually references to validate against
- See if we can create a Github action that automatically reruns the script on the files

**Comment by shadowdoc** [comment]
Looks like a reasonable plan. Should we also include in the specification updated .vscode settings such that we have conventions around file names in the development environment. 

The current setting is *.cde.json => current schema.

I propose the following:
*.rdes.json => cde_set.schema.json
*.rde.json => cde_element.schema.json
*.rdes_list.json => cde_set_list.schema.json
*.rde_list.json => cde_element_list.schema.json

**Comment by shadowdoc** [comment]
Following committee discussion we decided:
- schema_version will be required in cde_set.schema.json
- element_version will be not be included in set or set_list
- element_version will be used ONLY in cde_element and cde_element_list

These conventions should be supported in the new deconstructed CDE schema.
