### ISSUE TITLE
Need to be able to refer to CDE Sets, Elements

### ISSUE THREAD

**Issue by talkasab** [RSNA/ACR-RSNA-CDEs#50]
Should to have a structure by which a Set definition can indicate that it includes an Element which isn't being defined within the Set.
I would propose that we define an `element_ref` structure of the form:
```json
{
  "ref_id": "RDE1234",
  "version_number": 1
}
```
and then make the `elements` component of the Set definition be able to refer to either our existing element objects or this new `element_ref`-type object.

**Comment by shadowdoc** [comment]
The documentation in the schema needs to be explicit that this is for PUT/POST and not for GET requests in the API.
